#tomcat
server:
    port: 8080
    servlet:
        # 访问路径
        context-path: /demo
        # session 过期时间
        session:
            timeout: 30m


#spring
spring:
    profiles:
        active: dev